### ISSUE TITLE
test_kde_predictor.py failing

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/acton#87]
$ ./test
................E..............
======================================================================
ERROR: KDEClassifier implements the scikit-learn interface.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ong017/Repo/acton/tests/test_kde_predictor.py", line 15, in test_sklearn_interface
    acton.kde_predictor.KDEClassifier)
  File "/Users/ong017/anaconda3/envs/astro/lib/python3.5/site-packages/sklearn/utils/estimator_checks.py", line 253, in check_estimator
    check_parameters_default_constructible(name, Estimator)
  File "/Users/ong017/anaconda3/envs/astro/lib/python3.5/site-packages/sklearn/utils/estimator_checks.py", line 1470, in check_parameters_default_constructible
    with ignore_warnings(category=DeprecationWarning):
  File "/Users/ong017/anaconda3/envs/astro/lib/python3.5/site-packages/sklearn/utils/testing.py", line 369, in __enter__
    clean_warning_registry()  # be safe and not propagate state + chaos
  File "/Users/ong017/anaconda3/envs/astro/lib/python3.5/site-packages/sklearn/utils/testing.py", line 762, in clean_warning_registry
    getattr(mod, reg).clear()
AttributeError: 'NoneType' object has no attribute 'clear'

----------------------------------------------------------------------
Ran 31 tests in 7.023s

FAILED (errors=1)

**Comment by MatthewJA** [comment]
Odd, succeeds on Travis: https://travis-ci.org/chengsoonong/acton/builds/202512217

What version of sklearn are you on?

**Comment by chengsoonong** [comment]
Strange isn't it?

$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> sklearn.__version__
'0.18.1'
>>>

**Comment by MatthewJA** [comment]
```
$ python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> sklearn.__version__
'0.18.1'
```

I have no idea what the problem is (and can't reproduce it).

**Comment by chengsoonong** [comment]
I'll try again when I've got more head space.
